; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = atmelavr
board = uno
framework = arduino
lib_ldf_mode = deep+
lib_deps = 
    Servo
    adafruit/RTClib

[env:uno_main]
build_src_filter = +<*> -<setupRTC.cpp> -<tuneServoPos.cpp>

[env:uno_rtc_setup]
build_src_filter = +<*> -<main.cpp> -<tuneServoPos.cpp>

[env:uno_servo_alignment]
build_src_filter = +<*> -<main.cpp> -<setupRTC.cpp>
